article_lab_css <- function() {
  v2_css <- if (get0("article_lab_design_v2", inherits = TRUE, ifnotfound = FALSE)) {
    c(
      "      body { background: #f5f7f8; }",
      "      .topbar.topbar-v2 {",
      "        height: 56px;",
      "        background: #ffffff;",
      "        border-bottom: 1px solid #d9dee3;",
      "        padding: 0 24px;",
      "      }",
      "      .topbar-v2 .brand { font-size: 18px; gap: 12px; }",
      "      .topbar-v2 .brand-mark { width: 30px; height: 30px; border-radius: 7px; font-size: 21px; }",
      "      .topbar-v2 .top-actions { gap: 10px; font-size: 13px; }",
      "      .v2-env-pill, .page-version-badge {",
      "        display: inline-flex;",
      "        align-items: center;",
      "        min-height: 24px;",
      "        padding: 3px 9px;",
      "        border: 1px solid #b7d7ba;",
      "        border-radius: 999px;",
      "        background: #eef7f0;",
      "        color: #166f14;",
      "        font-size: 12px;",
      "        font-weight: 750;",
      "      }",
      "      .app-shell.app-shell-v2 {",
      "        grid-template-columns: 252px minmax(720px, 1fr) 308px;",
      "        min-height: calc(100vh - 56px);",
      "        background: #f5f7f8;",
      "      }",
      "      .app-shell-v2 .sidebar,",
      "      .app-shell-v2 .guide {",
      "        background: #ffffff;",
      "        border-color: #d9dee3;",
      "      }",
      "      .app-shell-v2 .sidebar { padding: 14px 12px; }",
      "      .app-shell-v2 .guide {",
      "        position: sticky;",
      "        top: 56px;",
      "        align-self: start;",
      "        max-height: calc(100vh - 56px);",
      "        overflow-y: auto;",
      "        padding: 20px 18px;",
      "      }",
      "      .app-shell-v2 .main {",
      "        max-width: 1060px;",
      "        margin: 0 auto;",
      "        padding: 24px 28px 44px;",
      "      }",
      "      .app-shell-v2.workflow-wide-layout { grid-template-columns: 252px minmax(900px, 1fr); }",
      "      .app-shell-v2.workflow-wide-layout .guide { display: none; }",
      "      .app-shell-v2 .main.workflow-wide-main { max-width: none; padding-right: 32px; }",
      "      .app-shell-v2.workflow-wide-layout .main { margin: 0; }",
      "      .app-shell-v2 .nav-item {",
      "        min-height: 40px;",
      "        border-radius: 8px;",
      "        padding: 6px 9px;",
      "        margin-bottom: 2px;",
      "      }",
      "      .app-shell-v2 button.nav-item:hover { background: #f2f5f3; }",
      "      .app-shell-v2 .nav-item.active {",
      "        background: #e8f4ea;",
      "        box-shadow: inset 3px 0 0 #1a8917;",
      "      }",
      "      .app-shell-v2 .nav-title { font-size: 14px; }",
      "      .app-shell-v2 .nav-copy { gap: 2px; }",
      "      .app-shell-v2 .nav-subtitle { font-size: 10px; color: #69737c; }",
      "      .app-shell-v2 .sidebar-nav-group { margin-bottom: 9px; }",
      "      .app-shell-v2 .sidebar-nav-label { margin-bottom: 5px; }",
      "      .app-shell-v2 .daily-goal {",
      "        border-color: #dfe5e8;",
      "        background: #fbfcfc;",
      "        border-radius: 8px;",
      "        padding: 11px;",
      "        margin-top: 10px;",
      "      }",
      "      .page-header {",
      "        display: flex;",
      "        justify-content: space-between;",
      "        align-items: flex-start;",
      "        gap: 18px;",
      "        margin-bottom: 16px;",
      "      }",
      "      .app-shell-v2 h1 { font-size: 25px; line-height: 1.15; }",
      "      .app-shell-v2 .page-subtitle { margin-top: 6px; font-size: 14px; max-width: 760px; }",
      "      .app-shell-v2 .lab-card,",
      "      .app-shell-v2 .status-card,",
      "      .app-shell-v2 .empty-state,",
      "      .app-shell-v2 .done-state,",
      "      .app-shell-v2 .rating-panel {",
      "        border-color: #dfe5e8;",
      "        border-radius: 8px;",
      "        box-shadow: 0 1px 2px rgba(20, 31, 43, .04);",
      "      }",
      "      .app-shell-v2 .lab-card {",
      "        max-width: none;",
      "        margin-top: 14px;",
      "        padding: 18px;",
      "      }",
      "      .app-shell-v2 .lab-card > .lab-card {",
      "        border: 0;",
      "        box-shadow: none;",
      "        padding: 0;",
      "        margin-top: 14px;",
      "        background: transparent;",
      "      }",
      "      .app-shell-v2 .lab-primary-work-card { padding: 16px 18px 18px; }",
      "      .lab-workflow-toolbar {",
      "        display: flex;",
      "        align-items: center;",
      "        justify-content: space-between;",
      "        gap: 18px;",
      "        padding: 13px 16px;",
      "        border: 1px solid #dfe5e8;",
      "        border-radius: 8px;",
      "        background: #ffffff;",
      "        box-shadow: 0 1px 2px rgba(20, 31, 43, .04);",
      "      }",
      "      .lab-workflow-eyebrow {",
      "        color: #69737c;",
      "        font-size: 11px;",
      "        font-weight: 750;",
      "        letter-spacing: .08em;",
      "        text-transform: uppercase;",
      "      }",
      "      .lab-workflow-title { font-size: 17px; font-weight: 760; margin-top: 2px; }",
      "      .lab-workflow-hint { color: #69737c; font-size: 13px; }",
      "      .app-shell-v2 .lab-actions {",
      "        padding: 12px 14px;",
      "        border: 1px solid #edf0f2;",
      "        border-radius: 8px;",
      "        background: #fbfcfc;",
      "        gap: 12px;",
      "      }",
      "      .app-shell-v2 .lab-actions .btn {",
      "        min-width: 132px;",
      "        height: 42px;",
      "        padding: 0 18px;",
      "      }",
      "      .app-shell-v2 .lab-actions .btn[id='research_remove_from_ranked'] { min-width: 258px; }",
      "      .app-shell-v2 .lab-actions-full-text {",
      "        display: grid;",
      "        grid-template-columns: repeat(5, minmax(172px, 1fr));",
      "        align-items: stretch;",
      "        gap: 12px 14px;",
      "        padding: 14px;",
      "      }",
      "      .app-shell-v2 .lab-actions-full-text .btn {",
      "        width: 100%;",
      "        min-width: 0;",
      "        height: 46px;",
      "        padding: 0 16px;",
      "        white-space: normal;",
      "        line-height: 1.15;",
      "      }",
      "      .app-shell-v2 .lab-full-text-choicebar {",
      "        align-items: flex-start;",
      "        justify-content: space-between;",
      "        gap: 18px;",
      "        margin-bottom: 18px;",
      "      }",
      "      .app-shell-v2 .lab-full-text-choice-row {",
      "        display: flex;",
      "        justify-content: flex-end;",
      "        align-items: stretch;",
      "        gap: 12px;",
      "        min-width: min(760px, 74%);",
      "      }",
      "      .app-shell-v2 .lab-full-text-choice-row .form-group {",
      "        flex: 1 1 0;",
      "        min-width: 260px;",
      "        margin-bottom: 0;",
      "      }",
      "      .app-shell-v2 .lab-full-text-choicebar .checkbox {",
      "        width: 100%;",
      "        margin-top: 0;",
      "        padding: 9px 14px;",
      "        border: 1px solid #d6dde2;",
      "        border-radius: 8px;",
      "        background: #ffffff;",
      "      }",
      "      .app-shell-v2 .lab-full-text-choicebar .checkbox label {",
      "        display: inline-flex;",
      "        align-items: center;",
      "        gap: 9px;",
      "        min-height: 22px;",
      "        margin: 0;",
      "        font-weight: 750;",
      "        color: #25282b;",
      "      }",
      "      .app-shell-v2 .lab-full-text-choicebar .checkbox input[type='checkbox'] {",
      "        position: static;",
      "        margin: 0;",
      "      }",
      "      .app-shell-v2 .lab-full-text-draft-meta {",
      "        margin: 0 0 12px;",
      "      }",
      "      .app-shell-v2 .lab-full-text-package-card.lab-selected-card .lab-full-text-choicebar .checkbox,",
      "      .app-shell-v2 .lab-full-text-package-card:has(input[type='checkbox']:checked) > .lab-full-text-choicebar .checkbox,",
      "      .app-shell-v2 .lab-outline-editor.lab-selected-card .lab-full-text-choicebar .checkbox,",
      "      .app-shell-v2 .lab-outline-editor:has(input[type='checkbox']:checked) > .lab-full-text-choicebar .checkbox {",
      "        border-color: #9bc99e;",
      "        background: #eef8ef;",
      "      }",
      "      .lab-collapsible-setup { padding: 0 !important; overflow: hidden; }",
      "      .lab-collapsible-setup > summary {",
      "        cursor: pointer;",
      "        padding: 14px 18px;",
      "        font-weight: 760;",
      "        list-style-position: inside;",
      "      }",
      "      .lab-collapsible-setup[open] > summary { border-bottom: 1px solid #edf0f2; }",
      "      .lab-collapsible-setup > .lab-setup-card { margin: 0; }",
      "      .app-shell-v2 table { font-size: 13px; }",
      "      .app-shell-v2 table thead th {",
      "        position: sticky;",
      "        top: 0;",
      "        background: #ffffff;",
      "        z-index: 1;",
      "      }",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_length,",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_filter {",
      "        margin: 12px 0 14px;",
      "        color: #2d3135;",
      "        font-size: 15px;",
      "        font-weight: 700;",
      "      }",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_length label {",
      "        display: inline-flex;",
      "        align-items: center;",
      "        gap: 9px;",
      "        margin: 0;",
      "        white-space: nowrap;",
      "      }",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_length select {",
      "        width: 76px;",
      "        height: 38px;",
      "        margin: 0;",
      "        padding: 4px 30px 4px 10px;",
      "        border-color: #bfc7cc;",
      "        border-radius: 6px;",
      "        font-size: 15px;",
      "        font-weight: 700;",
      "      }",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_filter label {",
      "        display: inline-flex;",
      "        align-items: center;",
      "        gap: 9px;",
      "        margin: 0;",
      "        white-space: nowrap;",
      "      }",
      "      .app-shell-v2 .dataTables_wrapper .dataTables_filter input {",
      "        height: 38px;",
      "        margin: 0;",
      "        border-color: #bfc7cc;",
      "        border-radius: 6px;",
      "      }",
      "      .app-shell-v2 .status-card { background: #ffffff; }",
      "      .app-shell-v2 .status-card .status-metric { color: #1a8917; font-size: 26px; }",
      "      .app-shell-v2:not(.workflow-wide-layout) .main {",
      "        max-width: 980px;",
      "        margin: 0 auto;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .tabs,",
      "      .app-shell-v2:not(.workflow-wide-layout) .article-card,",
      "      .app-shell-v2:not(.workflow-wide-layout) .rating-panel {",
      "        max-width: none;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .tabs {",
      "        margin-top: 18px;",
      "        border-bottom-color: #dfe5e8;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .article-card {",
      "        grid-template-columns: minmax(0, 1fr) 230px;",
      "        gap: 34px;",
      "        align-items: center;",
      "        margin-top: 0;",
      "        padding: 28px 30px;",
      "        min-height: 220px;",
      "        border: 1px solid #dfe5e8;",
      "        border-top: 0;",
      "        border-radius: 0 0 8px 8px;",
      "        box-shadow: 0 1px 2px rgba(20, 31, 43, .04);",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .article-title {",
      "        max-width: 650px;",
      "        font-size: 30px;",
      "        line-height: 1.12;",
      "        margin-bottom: 12px;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .article-subtitle {",
      "        max-width: 680px;",
      "        font-size: 19px;",
      "        line-height: 1.35;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .thumbnail-wrap .shiny-image-output,",
      "      .app-shell-v2:not(.workflow-wide-layout) .thumbnail-wrap img,",
      "      .app-shell-v2:not(.workflow-wide-layout) .thumbnail-placeholder {",
      "        width: 230px !important;",
      "        height: 153px !important;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .thumbnail-placeholder {",
      "        background: #fbfcfc;",
      "        font-size: 12px;",
      "      }",
      "      .app-shell-v2:not(.workflow-wide-layout) .rating-panel {",
      "        margin-top: 14px;",
      "        padding: 18px 24px;",
      "      }",
      "      .app-shell-v2 .rating-buttons .btn {",
      "        height: 58px;",
      "        display: grid;",
      "        place-items: center;",
      "        gap: 1px;",
      "      }",
      "      .rating-score-value {",
      "        display: block;",
      "        font-size: 24px;",
      "        font-weight: 760;",
      "        line-height: 1;",
      "      }",
      "      .rating-score-shortcut,",
      "      .rating-action-shortcut {",
      "        display: block;",
      "        color: #69737c;",
      "        font-size: 11px;",
      "        font-weight: 700;",
      "        line-height: 1.15;",
      "        margin-top: 3px;",
      "      }",
      "      .app-shell-v2 .rating-actions .btn {",
      "        min-height: 58px;",
      "        width: 100%;",
      "        display: inline-grid;",
      "        align-content: center;",
      "      }",
      "      .app-shell-v2 .rating-actions {",
      "        display: grid;",
      "        grid-template-columns: repeat(5, minmax(0, 1fr));",
      "        gap: 10px;",
      "        align-items: stretch;",
      "      }",
      "      .app-shell-v2 .rating-actions > div:first-child,",
      "      .rating-shortcut-buttons {",
      "        display: contents;",
      "      }",
      "      .shortcut-key-button {",
      "        min-height: 58px;",
      "        width: 100%;",
      "        padding: 6px 10px;",
      "        border: 1px solid #d9e0e3;",
      "        border-radius: 7px;",
      "        background: #f8faf9;",
      "        color: #1b1f23;",
      "        display: inline-grid;",
      "        grid-template-columns: auto auto;",
      "        align-items: center;",
      "        gap: 7px;",
      "        font: inherit;",
      "        line-height: 1;",
      "        box-shadow: none;",
      "      }",
      "      .shortcut-key-button:hover {",
      "        border-color: #bfccd1;",
      "        background: #fff;",
      "      }",
      "      .shortcut-key {",
      "        min-width: 28px;",
      "        padding: 5px 7px;",
      "        border: 1px solid #c8d1d5;",
      "        border-radius: 5px;",
      "        background: #fff;",
      "        color: #202426;",
      "        font-size: 12px;",
      "        font-weight: 760;",
      "        text-align: center;",
      "      }",
      "      .shortcut-key-label {",
      "        color: #69737c;",
      "        font-size: 12px;",
      "        font-weight: 700;",
      "      }"
    )
  } else {
    character()
  }

  HTML(paste(c(
    "      :root {",
    "        --green: #1a8917;",
    "        --green-soft: #eef7f0;",
    "        --ink: #191919;",
    "        --muted: #6b6b6b;",
    "        --line: #e6e6e6;",
    "        --panel: #f8f8f8;",
    "      }",
    "      body {",
    "        margin: 0;",
    "        color: var(--ink);",
    "        background: #fff;",
    "        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;",
    "      }",
    "      .container-fluid { padding: 0; }",
    "      .topbar {",
    "        height: 50px;",
    "        border-bottom: 1px solid var(--line);",
    "        display: flex;",
    "        align-items: center;",
    "        justify-content: space-between;",
    "        padding: 0 22px;",
    "      }",
    "      .brand { display: flex; align-items: center; gap: 14px; font-size: 20px; font-weight: 700; }",
    "      .brand-mark {",
    "        width: 32px; height: 32px; border-radius: 6px; background: #197b30; color: #fff;",
    "        display: grid; place-items: center; font-family: Georgia, serif; font-size: 23px; font-weight: 700;",
    "      }",
    "      .top-actions { color: var(--muted); display: flex; gap: 22px; align-items: center; font-size: 15px; }",
    "      .app-shell { display: grid; grid-template-columns: 230px minmax(560px, 1fr) 300px; min-height: calc(100vh - 50px); }",
    "      .sidebar, .guide { border-right: 1px solid var(--line); padding: 20px 18px; position: relative; }",
    "      .guide { border-right: 0; border-left: 1px solid var(--line); }",
    "      .sidebar-nav-group { margin-bottom: 18px; }",
    "      .sidebar-nav-label {",
    "        margin: 0 0 10px;",
    "        color: #8a8a8a;",
    "        font-size: 11px;",
    "        font-weight: 750;",
    "        letter-spacing: .08em;",
    "        text-transform: uppercase;",
    "      }",
    "      .nav-item {",
    "        min-height: 50px;",
    "        display: grid;",
    "        grid-template-columns: 18px minmax(0, 1fr);",
    "        gap: 10px;",
    "        align-items: start;",
    "        padding: 10px 12px;",
    "        border-radius: 10px;",
    "        color: var(--ink);",
    "        font-size: 15px;",
    "        margin-bottom: 6px;",
    "      }",
    "      button.nav-item {",
    "        width: 100%;",
    "        border: 0;",
    "        background: transparent;",
    "        text-align: left;",
    "      }",
    "      button.nav-item:hover { background: #f5f5f5; }",
    "      button.nav-item:focus { outline: none; box-shadow: none; }",
    "      button.nav-item:disabled { opacity: .78; cursor: default; }",
    "      .nav-item.active { background: var(--green-soft); }",
    "      .nav-icon {",
    "        font-size: 16px;",
    "        line-height: 1;",
    "        margin-top: 2px;",
    "      }",
    "      .nav-copy {",
    "        display: grid;",
    "        gap: 4px;",
    "        min-width: 0;",
    "      }",
    "      .nav-title {",
    "        font-size: 15px;",
    "        font-weight: 700;",
    "        line-height: 1.15;",
    "      }",
    "      .nav-subtitle {",
    "        color: var(--muted);",
    "        font-size: 12px;",
    "        line-height: 1.3;",
    "      }",
    "      .stage-one-hero, .evidence-idea-header {",
    "        display: flex; align-items: center; justify-content: space-between; gap: 28px;",
    "      }",
    "      .stage-one-hero h2, .evidence-idea-header h2 { margin: 4px 0 8px; }",
    "      .stage-one-hero p, .evidence-idea-header p { margin: 0; max-width: 690px; color: var(--muted); }",
    "      .stage-one-kicker {",
    "        color: var(--green); font-size: 11px; font-weight: 800; letter-spacing: .09em; text-transform: uppercase;",
    "      }",
    "      .placeholder-action:disabled { opacity: .62; cursor: not-allowed; }",
    "      .stage-one-count, .evidence-readiness {",
    "        border: 1px solid var(--line); border-radius: 999px; padding: 7px 11px; color: var(--muted); font-size: 12px; white-space: nowrap;",
    "      }",
    "      .evidence-readiness { display: grid; gap: 2px; border-radius: 9px; padding: 10px 14px; }",
    "      .evidence-readiness strong { color: var(--ink); font-size: 14px; }",
    "      .stage-one-empty { text-align: center; padding: 28px 18px 10px; }",
    "      .stage-one-empty > p { color: var(--muted); }",
    "      .stage-one-empty-icon {",
    "        width: 44px; height: 44px; display: grid; place-items: center; margin: 0 auto 10px; border-radius: 12px; background: var(--green-soft); color: var(--green); font-weight: 800;",
    "      }",
    "      .placeholder-record { max-width: 720px; margin: 24px auto 0; padding: 16px; border: 1px dashed var(--line); border-radius: 10px; text-align: left; background: var(--panel); }",
    "      .placeholder-record-title { font-weight: 750; margin-bottom: 12px; }",
    "      .placeholder-meta-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; }",
    "      .placeholder-meta-grid div { display: grid; gap: 4px; }",
    "      .placeholder-meta-grid span { color: var(--muted); font-size: 11px; text-transform: uppercase; letter-spacing: .05em; }",
    "      .placeholder-meta-grid strong { font-size: 13px; }",
    "      .evidence-action-bar { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 14px; padding: 14px; border: 1px solid var(--line); border-radius: 8px; background: var(--panel); }",
    "      .evidence-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }",
    "      .evidence-section p { color: var(--muted); min-height: 40px; }",
    "      .evidence-empty-line { padding: 13px 0 2px; border-top: 1px solid var(--line); color: var(--muted); font-size: 13px; }",
    "      .stage-one-note { margin-top: 14px; padding: 12px 14px; border-left: 3px solid var(--green); background: var(--green-soft); color: var(--muted); font-size: 13px; }",
    "      .stage-one-note strong { color: var(--ink); }",
    "      .title-lab-shell { margin-bottom: 14px; border: 1px solid var(--line); border-radius: 9px; background: #fff; overflow: hidden; }",
    "      .title-lab-flow { display: flex; align-items: center; gap: 0; padding: 11px 16px; border-bottom: 1px solid var(--line); color: var(--muted); font-size: 12px; }",
    "      .title-lab-flow span { display: inline-flex; align-items: center; }",
    "      .title-lab-flow span:not(:last-child)::after { content: '\u2192'; margin: 0 9px; color: #a1a1a1; }",
    "      .title-lab-tabs { display: flex; gap: 4px; padding: 6px; }",
    "      .title-lab-tab { border: 0; border-radius: 7px; background: transparent; padding: 10px 15px; color: var(--muted); font-size: 14px; font-weight: 700; }",
    "      .title-lab-tab:hover { background: var(--panel); color: var(--ink); }",
    "      .title-lab-tab.active { background: var(--green-soft); color: var(--green); box-shadow: inset 0 -2px 0 var(--green); }",
    "      .research-summary-entry { align-items: center; justify-content: flex-start; margin-top: 12px; }",
    "      .research-summary-entry .lab-status-copy { margin: 0; }",
    "      .daily-goal {",
    "        border: 1px solid var(--line); border-radius: 8px; padding: 14px 18px;",
    "        max-width: none;",
    "        position: static;",
    "        margin-top: 18px;",
    "      }",
    "      .daily-goal.static-card {",
    "        position: static;",
    "        max-width: none;",
    "        margin-top: 18px;",
    "      }",
    "      .article-lab-helper {",
    "        display: grid;",
    "        gap: 8px;",
    "      }",
    "      .daily-goal strong { display: block; margin-bottom: 8px; }",
    "      .daily-goal .num { color: var(--green); font-weight: 700; }",
    "      .progress-track { height: 7px; background: #e9e9e9; border-radius: 99px; overflow: hidden; margin: 12px 0 8px; }",
    "      .progress-fill { height: 100%; background: var(--green); border-radius: 99px; width: 0%; }",
    "      .main { padding: 22px 30px 18px; max-width: 920px; width: 100%; margin: 0 auto; }",
    "      .app-shell.workflow-wide-layout { grid-template-columns: 230px minmax(860px, 1fr); }",
    "      .app-shell.workflow-wide-layout .guide,",
    "      .guide.guide-hidden { display: none; }",
    "      .main.workflow-wide-main {",
    "        max-width: 1280px;",
    "        padding-right: 34px;",
    "      }",
    "      .main.workflow-wide-main .page-subtitle,",
    "      .main.workflow-wide-main .lab-card,",
    "      .main.workflow-wide-main .empty-state {",
    "        max-width: none;",
    "      }",
    "      h1 { margin: 0; font-size: 26px; line-height: 1.05; font-weight: 750; letter-spacing: 0; }",
    "      .progress-line { margin-top: 5px; color: var(--muted); font-size: 16px; }",
    "      .progress-line .current { color: var(--green); font-weight: 750; }",
    "      .mode-line { margin-top: 5px; color: var(--muted); font-size: 12px; }",
    "      .mode-line strong { color: var(--green); font-weight: 650; }",
    "      .v2-debug-banner {",
    "        max-width: 760px;",
    "        margin-top: 8px;",
    "        padding: 8px 10px;",
    "        border: 1px solid #b8d8ba;",
    "        border-radius: 6px;",
    "        background: #f4fbf4;",
    "        color: #3f6f42;",
    "        font-size: 11px;",
    "        line-height: 1.35;",
    "        overflow-wrap: anywhere;",
    "      }",
    "      .v2-debug-banner.error {",
    "        border-color: #d95f5f;",
    "        background: #fff5f5;",
    "        color: #a83232;",
    "      }",
    "      .v2-debug-banner strong { color: inherit; font-weight: 700; }",
    "      .v2-paused-warning {",
    "        max-width: 760px;",
    "        margin-top: 8px;",
    "        padding: 9px 11px;",
    "        border: 1px solid #e0c36f;",
    "        border-radius: 6px;",
    "        background: #fff9e8;",
    "        color: #6f5600;",
    "        font-size: 12px;",
    "        line-height: 1.35;",
    "      }",
    "      .tabs { display: flex; gap: 38px; border-bottom: 1px solid var(--line); margin-top: 14px; max-width: 760px; box-sizing: border-box; }",
    "      .tab { padding-bottom: 8px; color: var(--muted); font-size: 15px; }",
    "      .tab.active { color: var(--ink); font-weight: 650; border-bottom: 2px solid var(--ink); }",
    "      .article-card {",
    "        display: grid;",
    "        grid-template-columns: minmax(0, 1fr) 170px;",
    "        gap: 32px;",
    "        align-items: center;",
    "        box-sizing: border-box;",
    "        width: 100%;",
    "        max-width: 760px;",
    "        margin-top: 0;",
    "        padding: 28px 0 30px;",
    "        border-bottom: 1px solid #f2f2f2;",
    "        background: #fff;",
    "      }",
    "      .article-title {",
    "        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;",
    "        font-size: 26px; line-height: 1.15; font-weight: 760; letter-spacing: 0; margin: 0 0 8px;",
    "      }",
    "      .article-subtitle { font-size: 18px; line-height: 1.35; color: var(--muted); margin: 0; }",
    "      .thumbnail-wrap { display: flex; justify-content: flex-end; align-items: center; }",
    "      .thumbnail-wrap .shiny-image-output {",
    "        width: 170px !important;",
    "        height: 113px !important;",
    "      }",
    "      .thumbnail-wrap img {",
    "        width: 170px; height: 113px; object-fit: cover; border-radius: 1px; display: block;",
    "      }",
    "      .thumbnail-placeholder {",
    "        width: 170px; height: 113px; border-radius: 1px; background: #fff; border: 1px dashed #cfcfcf;",
    "        box-sizing: border-box; color: #777; font-size: 11px; display: grid; place-items: center; text-align: center;",
    "        padding: 8px;",
    "        white-space: pre-line;",
    "      }",
    "      .thumbnail-placeholder.error {",
    "        border-color: #d95f5f;",
    "        color: #a83232;",
    "        background: #fff5f5;",
    "      }",
    "      .article-card.thumbnail-only {",
    "        grid-template-columns: 170px;",
    "        justify-content: center;",
    "        align-items: center;",
    "        max-width: 760px;",
    "        padding-top: 18px;",
    "      }",
    "      .article-card.thumbnail-only .thumbnail-wrap { justify-content: center; }",
    "      .article-card.thumbnail-only .thumbnail-wrap .shiny-image-output,",
    "      .article-card.thumbnail-only .thumbnail-wrap img,",
    "      .article-card.thumbnail-only .thumbnail-placeholder {",
    "        width: 170px !important;",
    "        height: 113px !important;",
    "      }",
    "      .article-card.text-only {",
    "        grid-template-columns: minmax(0, 1fr);",
    "        max-width: 760px;",
    "      }",
    "      .article-card.text-only .article-title {",
    "        font-size: 30px;",
    "        line-height: 1.12;",
    "        margin-bottom: 10px;",
    "      }",
    "      .article-card.text-only .article-subtitle {",
    "        font-size: 20px;",
    "        line-height: 1.35;",
    "      }",
    "      .dimension-verification-title {",
    "        color: #9a9a9a;",
    "        font-size: 12px;",
    "        line-height: 1.25;",
    "        font-weight: 400;",
    "        max-width: 360px;",
    "        cursor: copy;",
    "        user-select: text;",
    "      }",
    "      .dimension-verification-title.copied { color: var(--green); }",
    "      .thumbnail-invalid-label { max-width: 130px; }",
    "      .rating-panel {",
    "        border: 1px solid var(--line);",
    "        border-radius: 8px;",
    "        box-sizing: border-box;",
    "        background: #fff;",
    "        margin-top: 12px;",
    "        max-width: 760px;",
    "        padding: 14px 20px;",
    "      }",
    "      .prompt { font-size: 15px; line-height: 1.22; font-weight: 680; margin-bottom: 10px; }",
    "      .note-row label { color: var(--muted); font-weight: 500; margin-bottom: 4px; font-size: 13px; }",
    "      .note-row input.form-control, .note-row textarea.form-control {",
    "        height: 40px; border: 1px solid #d9d9d9; border-radius: 8px;",
    "        box-shadow: none; font-size: 14px; padding: 8px 12px;",
    "      }",
    "      .note-row textarea.form-control { min-height: 54px; resize: vertical; }",
    "      .note-row input.form-control:focus, .note-row textarea.form-control:focus { border-color: var(--green); box-shadow: 0 0 0 3px rgba(26, 137, 23, .12); }",
    "      .scale-labels { display: flex; justify-content: space-between; color: var(--muted); margin: 9px 4px 5px; font-size: 13px; }",
    "      .rating-buttons { display: grid; grid-template-columns: repeat(5, minmax(64px, 1fr)); gap: 10px; }",
    "      .rating-buttons .btn {",
    "        height: 40px; border: 1px solid #d8d8d8; border-radius: 7px; background: #fff;",
    "        color: var(--ink); font-size: 19px; font-weight: 650; box-shadow: none;",
    "      }",
    "      .rating-buttons .btn:hover {",
    "        border-color: var(--green); color: var(--green); background: #f6fbf6;",
    "      }",
    "      .rating-buttons .btn.rating-confirm {",
    "        border-color: var(--green); color: #fff; background: var(--green);",
    "      }",
    "      .rating-buttons .btn:focus {",
    "        border-color: #d8d8d8; color: var(--ink); background: #fff; outline: none; box-shadow: none;",
    "      }",
    "      .rating-actions { display: flex; gap: 12px; justify-content: space-between; align-items: center; margin-top: 10px; }",
    "      .rating-actions .btn {",
    "        min-width: 136px; height: 34px; border-radius: 7px; font-size: 13px; font-weight: 650; box-shadow: none;",
    "      }",
    "      .dimension-rubric { display: grid; gap: 8px; margin-top: 10px; }",
    "      .dimension-row {",
    "        border: 1px solid var(--line);",
    "        border-radius: 8px;",
    "        padding: 9px 10px;",
    "        display: grid;",
    "        grid-template-columns: minmax(0, 1fr) auto;",
    "        gap: 12px;",
    "        align-items: center;",
    "      }",
    "      .dimension-row.active { border-color: var(--green); background: var(--green-soft); }",
    "      .dimension-name { font-size: 13px; font-weight: 720; margin-bottom: 2px; }",
    "      .dimension-question { color: var(--muted); font-size: 12px; line-height: 1.25; }",
    "      .dimension-buttons { display: flex; gap: 6px; flex-wrap: nowrap; }",
    "      .dimension-choice.btn {",
    "        min-width: 42px; min-height: 32px; padding: 4px 8px; border-radius: 7px;",
    "        border: 1px solid #d8d8d8; background: #fff; color: var(--ink);",
    "        font-weight: 650; box-shadow: none;",
    "      }",
    "      .dimension-choice.flag-choice { min-width: 64px; display: grid; gap: 1px; justify-items: center; line-height: 1.05; }",
    "      .dimension-choice-label { display: block; }",
    "      .dimension-choice-shortcut { display: block; color: #a0a0a0; font-size: 10px; font-weight: 500; }",
    "      .dimension-choice.selected,",
    "      .dimension-choice.dimension-confirm { border-color: var(--green); background: var(--green); color: #fff; }",
    "      .dimension-choice.selected .dimension-choice-shortcut,",
    "      .dimension-choice.dimension-confirm .dimension-choice-shortcut { color: rgba(255,255,255,.72); }",
    "      .dimension-pass-header { display: grid; gap: 6px; margin-bottom: 12px; }",
    "      .dimension-pass-kicker { color: var(--green); font-size: 12px; font-weight: 750; text-transform: uppercase; letter-spacing: 0; }",
    "      .dimension-pass-name { font-size: 22px; line-height: 1.1; font-weight: 760; }",
    "      .dimension-pass-question { font-size: 15px; line-height: 1.28; font-weight: 650; }",
    "      .dimension-pass-focus { color: var(--muted); font-size: 13px; }",
    "      .dimension-scale-list { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 6px; margin: 8px 0 10px; }",
    "      .dimension-scale-item {",
    "        border: 1px solid var(--line); border-radius: 7px; padding: 7px 8px; min-height: 46px;",
    "        font-size: 12px; line-height: 1.2; text-align: left; box-shadow: none;",
    "      }",
    "      .dimension-scale-item strong { display: block; color: var(--green); font-size: 13px; margin-bottom: 2px; }",
    "      .dimension-scale-shortcut { display: block; color: #a0a0a0; font-size: 10px; font-weight: 500; margin-top: 4px; }",
    "      .dimension-scale-choice { width: 100%; background: #fff; cursor: pointer; transition: background-color .12s ease, border-color .12s ease, color .12s ease; }",
    "      .dimension-scale-choice:hover:not(:disabled) { border-color: #bdbdbd; background: #fafafa; }",
    "      .dimension-scale-choice:disabled { cursor: not-allowed; opacity: .55; }",
    "      .dimension-scale-choice.dimension-confirm,",
    "      .dimension-scale-choice.selected,",
    "      .dimension-scale-choice.dimension-confirm strong,",
    "      .dimension-scale-choice.selected strong { border-color: var(--green); color: #fff; }",
    "      .dimension-scale-choice.dimension-confirm .dimension-scale-shortcut,",
    "      .dimension-scale-choice.selected .dimension-scale-shortcut { color: rgba(255,255,255,.72); }",
    "      .dimension-scale-choice.dimension-confirm,",
    "      .dimension-scale-choice.selected { background: var(--green); }",
    "      .dimension-flag-scale { grid-template-columns: repeat(3, minmax(0, 1fr)); }",
    "      .dimension-flag-scale .dimension-scale-item strong { color: var(--ink); }",
    "      .btn-default { border-color: #d8d8d8; background: #fff; color: var(--ink); }",
    "      .btn-default:hover { border-color: #bdbdbd; background: #fafafa; }",
    "      .next-dimension-cta {",
    "        margin-top: 12px;",
    "        padding: 14px 16px;",
    "        border: 1px solid #cfe4d2;",
    "        border-radius: 8px;",
    "        background: #f5fbf6;",
    "        display: grid;",
    "        gap: 10px;",
    "      }",
    "      .next-dimension-copy {",
    "        color: var(--muted);",
    "        font-size: 13px;",
    "        line-height: 1.35;",
    "      }",
    "      .next-dimension-cta .btn {",
    "        width: 100%;",
    "        min-height: 46px;",
    "        border-radius: 8px;",
    "        border: 1px solid var(--green);",
    "        background: var(--green);",
    "        color: #fff;",
    "        font-size: 15px;",
    "        font-weight: 700;",
    "        box-shadow: none;",
    "      }",
    "      .next-dimension-cta .btn:hover {",
    "        border-color: #166f14;",
    "        background: #166f14;",
    "        color: #fff;",
    "      }",
    "      .next-dimension-cta .btn:focus {",
    "        border-color: #166f14;",
    "        background: #166f14;",
    "        color: #fff;",
    "        outline: none;",
    "        box-shadow: 0 0 0 3px rgba(26, 137, 23, .14);",
    "      }",
    "      .shortcut-copy { color: var(--muted); font-size: 13px; }",
    "      .page-subtitle {",
    "        margin-top: 8px;",
    "        color: var(--muted);",
    "        font-size: 16px;",
    "        line-height: 1.4;",
    "        max-width: 760px;",
    "      }",
    "      .lab-card,",
    "      .status-card,",
    "      .empty-state {",
    "        border: 1px solid var(--line);",
    "        border-radius: 8px;",
    "        background: #fff;",
    "      }",
    "      .lab-card {",
    "        max-width: 760px;",
    "        margin-top: 18px;",
    "        padding: 18px 20px 20px;",
    "      }",
    "      .lab-card > .lab-card {",
    "        margin-top: 14px;",
    "        max-width: none;",
    "        background: #fbfbfb;",
    "      }",
    "      .lab-section-card { padding-bottom: 16px; }",
    "      .lab-card h2 {",
    "        margin: 0 0 12px;",
    "        font-size: 19px;",
    "        font-weight: 760;",
    "      }",
    "      .lab-card h3 {",
    "        margin: 0 0 10px;",
    "        font-size: 17px;",
    "        font-weight: 730;",
    "      }",
    "      .lab-section-header {",
    "        display: flex;",
    "        justify-content: space-between;",
    "        gap: 14px;",
    "        align-items: flex-start;",
    "        margin-bottom: 14px;",
    "      }",
    "      .lab-section-copy {",
    "        margin: 0;",
    "        color: var(--muted);",
    "        font-size: 14px;",
    "        line-height: 1.4;",
    "      }",
    "      .article-inbox-capture { border-top: 3px solid var(--green); }",
    "      .article-inbox-capture .lab-grid { margin-top: 0; }",
    "      .article-inbox-divider { display: flex; align-items: center; gap: 12px; margin: 22px 0 14px; color: var(--muted); font-size: 12px; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; }",
    "      .article-inbox-divider::before, .article-inbox-divider::after { content: ''; height: 1px; flex: 1; background: var(--line); }",
    "      .article-candidate-editor { margin-top: 18px; padding-top: 18px; border-top: 1px solid var(--line); }",
    "      .article-inbox-empty { padding: 24px; text-align: center; color: var(--muted); }",
    "      .article-inbox-empty h2, .article-inbox-empty h3 { color: var(--ink); }",
    "      .candidate-provenance { display: grid; gap: 5px; padding: 10px 0; }",
    "      .candidate-provenance span { color: var(--muted); font-size: 12px; }",
    "      .evidence-source-row { display: flex; justify-content: space-between; gap: 12px; padding: 12px 0; border-top: 1px solid var(--line); }",
    "      .evidence-source-row span { color: var(--muted); font-size: 12px; }",
    "      .lab-count-badge {",
    "        display: inline-flex;",
    "        align-items: center;",
    "        justify-content: center;",
    "        padding: 4px 10px;",
    "        border-radius: 999px;",
    "        background: #eef4ff;",
    "        color: #2757a3;",
    "        font-size: 12px;",
    "        font-weight: 700;",
    "        white-space: nowrap;",
    "      }",
    "      .lab-grid {",
    "        display: grid;",
    "        grid-template-columns: repeat(2, minmax(0, 1fr));",
    "        gap: 12px 14px;",
    "        margin-top: 14px;",
    "      }",
    "      .lab-field label {",
    "        display: block;",
    "        color: var(--muted);",
    "        font-size: 13px;",
    "        font-weight: 600;",
    "        margin-bottom: 6px;",
    "      }",
    "      .lab-field .form-control {",
    "        border-radius: 8px;",
    "        border: 1px solid #d9d9d9;",
    "        box-shadow: none;",
    "      }",
    "      .lab-field .form-control:focus {",
    "        border-color: var(--green);",
    "        box-shadow: 0 0 0 3px rgba(26, 137, 23, .12);",
    "      }",
    "      .lab-editor-textarea textarea.form-control {",
    "        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace;",
    "        font-size: 13px;",
    "        line-height: 1.55;",
    "        white-space: pre-wrap;",
    "        tab-size: 2;",
    "      }",
    "      .lab-actions {",
    "        display: flex;",
    "        gap: 10px;",
    "        flex-wrap: wrap;",
    "        margin-top: 14px;",
    "        align-items: center;",
    "      }",
    "      .lab-actions-split {",
    "        justify-content: space-between;",
    "      }",
    "      .lab-actions input[type='checkbox'] {",
    "        margin-top: 0;",
    "      }",
    "      .lab-actions .checkbox {",
    "        margin: 0 12px 0 0;",
    "      }",
    "      .lab-actions .btn {",
    "        min-width: 138px;",
    "        height: 38px;",
    "        border-radius: 8px;",
    "        box-shadow: none;",
    "        font-weight: 650;",
    "      }",
    "      .lab-actions .btn.lab-primary {",
    "        border-color: var(--green);",
    "        background: var(--green);",
    "        color: #fff;",
    "      }",
    "      .lab-actions .btn.lab-primary:hover,",
    "      .lab-actions .btn.lab-primary:focus {",
    "        border-color: #166f14;",
    "        background: #166f14;",
    "        color: #fff;",
    "      }",
    "      .lab-actions .btn.lab-secondary {",
    "        border-color: #d8d8d8;",
    "        background: #fff;",
    "        color: var(--ink);",
    "      }",
    "      .lab-actions .btn.lab-secondary:hover,",
    "      .lab-actions .btn.lab-secondary:focus {",
    "        border-color: #bdbdbd;",
    "        background: #fafafa;",
    "        color: var(--ink);",
    "      }",
    "      .lab-actions .btn.lab-danger {",
    "        border-color: #e3c7b0;",
    "        background: #fff8f2;",
    "        color: #8a5200;",
    "      }",
    "      .lab-actions .btn.lab-danger:hover,",
    "      .lab-actions .btn.lab-danger:focus {",
    "        border-color: #c98f5a;",
    "        background: #fff0df;",
    "        color: #713f00;",
    "      }",
    "      .lab-actions .btn[disabled],",
    "      .lab-actions .btn.disabled {",
    "        opacity: .55;",
    "        cursor: not-allowed;",
    "        pointer-events: none;",
    "      }",
    "      .lab-actions .btn.lab-primary.loading,",
    "      .lab-actions .btn.lab-primary.loading:hover,",
    "      .lab-actions .btn.lab-primary.loading:focus {",
    "        border-color: #166f14;",
    "        background: #166f14;",
    "        color: #fff;",
    "        cursor: wait;",
    "      }",
    "      .lab-actions .btn.lab-primary.loading[disabled] {",
    "        opacity: 1;",
    "      }",
    "      .button-spinner {",
    "        display: inline-block;",
    "        width: 14px;",
    "        height: 14px;",
    "        margin-right: 8px;",
    "        border: 2px solid rgba(255,255,255,.34);",
    "        border-top-color: #fff;",
    "        border-radius: 50%;",
    "        vertical-align: -2px;",
    "        animation: lab-spin .75s linear infinite;",
    "      }",
    "      @keyframes lab-spin {",
    "        from { transform: rotate(0deg); }",
    "        to { transform: rotate(360deg); }",
    "      }",
    "      .lab-table {",
    "        width: 100%;",
    "        border-collapse: collapse;",
    "        margin-top: 6px;",
    "      }",
    "      .lab-table-wrap {",
    "        width: 100%;",
    "        overflow-x: auto;",
    "      }",
    "      .lab-table th,",
    "      .lab-table td {",
    "        padding: 10px 8px;",
    "        border-bottom: 1px solid #f0f0f0;",
    "        text-align: left;",
    "        vertical-align: top;",
    "        font-size: 13px;",
    "        line-height: 1.35;",
    "      }",
    "      .lab-table th {",
    "        color: var(--muted);",
    "        font-size: 12px;",
    "        font-weight: 700;",
    "        text-transform: uppercase;",
    "        letter-spacing: .01em;",
    "      }",
    "      .lab-table tbody tr {",
    "        transition: background-color .12s ease, box-shadow .12s ease;",
    "      }",
    "      .lab-table tbody tr.lab-selected-row,",
    "      .lab-table tbody tr:has(input[type='checkbox']:checked) {",
    "        background: #f2faf3;",
    "        box-shadow: inset 3px 0 0 var(--green);",
    "      }",
    "      .lab-table td.score-cell {",
    "        font-variant-numeric: tabular-nums;",
    "        white-space: nowrap;",
    "      }",
    "      .lab-table td.score-strong {",
    "        font-size: 18px;",
    "        font-weight: 760;",
    "      }",
    "      .lab-table td.select-cell {",
    "        width: 56px;",
    "      }",
    "      .lab-table th.title-col,",
    "      .lab-table td.title-cell {",
    "        width: 34%;",
    "      }",
    "      .lab-table th.notes-col,",
    "      .lab-table td.notes-cell {",
    "        width: 24%;",
    "      }",
    "      .lab-table th.subtitle-col,",
    "      .lab-table td.subtitle-cell {",
    "        width: 34%;",
    "      }",
    "      .lab-table th.signals-col,",
    "      .lab-table td.signals-cell {",
    "        width: 24%;",
    "      }",
    "      .lab-table th.score-col,",
    "      .lab-table td.score-cell,",
    "      .lab-table th.trust-col,",
    "      .lab-table td.trust-cell,",
    "      .lab-table th.status-col,",
    "      .lab-table td.status-cell {",
    "        white-space: nowrap;",
    "      }",
    "      .scored-table .notes-cell .form-control {",
    "        min-width: 220px;",
    "      }",
    "      .lab-table .shiny-input-container {",
    "        width: 100%;",
    "        margin-bottom: 0;",
    "      }",
    "      .lab-table .checkbox {",
    "        margin: 0;",
    "      }",
    "      .lab-table .form-control {",
    "        min-height: 34px;",
    "      }",
    "      table.dataTable.research-source-table {",
    "        width: 100% !important;",
    "        table-layout: fixed;",
    "      }",
    "      table.dataTable.research-source-table tbody td {",
    "        vertical-align: middle;",
    "      }",
    "      table.dataTable.research-source-table tbody tr.selected,",
    "      table.dataTable.research-source-table tbody tr.selected > * {",
    "        background-color: #edf8ef !important;",
    "        color: var(--ink) !important;",
    "      }",
    "      table.dataTable.research-source-table .research-source-title,",
    "      table.dataTable.research-source-table .research-source-main {",
    "        display: block;",
    "        white-space: nowrap;",
    "        overflow: hidden;",
    "        text-overflow: ellipsis;",
    "      }",
    "      table.dataTable.research-source-table .research-source-title,",
    "      table.dataTable.research-source-table .research-source-main { max-width: 100%; }",
    "      table.dataTable.research-source-table .research-source-links {",
    "        white-space: nowrap;",
    "      }",
    "      .lab-table-footer {",
    "        margin-top: 10px;",
    "        color: var(--muted);",
    "        font-size: 13px;",
    "      }",
    "      .lab-badge {",
    "        display: inline-flex;",
    "        align-items: center;",
    "        gap: 6px;",
    "        padding: 4px 8px;",
    "        border-radius: 999px;",
    "        font-size: 12px;",
    "        font-weight: 650;",
    "        line-height: 1;",
    "        background: #f4f6f4;",
    "        color: #35523b;",
    "      }",
    "      .lab-badge.mobile_safe,",
    "      .lab-badge.good { background: #edf8ef; color: #1a6d27; }",
    "      .lab-badge.long_but_allowed { background: #fff6e6; color: #8a5a00; }",
    "      .lab-badge.very_long_but_allowed { background: #fff1df; color: #9a4f00; }",
    "      .lab-badge.too_long { background: #fdecec; color: #9b2727; }",
    "      .lab-badge.ready_for_api_scoring { background: #edf8ef; color: #1a6d27; }",
    "      .lab-badge.api_scored { background: #eef4ff; color: #2757a3; }",
    "      .lab-badge.approved_for_subtitle { background: #f0ebff; color: #5a33a2; }",
    "      .lab-badge.ready_for_thumbnail { background: #e9f7f4; color: #166f62; }",
    "      .lab-badge.ready_for_outline { background: #e8f4ea; color: #1f6c2c; }",
    "      .lab-badge.ready_for_draft,",
    "      .lab-badge.ready_for_review_publish { background: #edf8ef; color: #1a6d27; }",
    "      .lab-badge.ready_to_publish,",
    "      .lab-badge.published { background: #e9f7f4; color: #166f62; }",
    "      .lab-badge.submitted { background: #eef4ff; color: #2757a3; }",
    "      .lab-badge.needs_changes { background: #fff6e6; color: #8a5a00; }",
    "      .lab-badge.subtitle_generated { background: #f5f5f5; color: #666; }",
    "      .lab-badge.subtitle_approved { background: #e9f7f4; color: #166f62; }",
    "      .lab-badge.subtitle_rejected { background: #fff3e6; color: #8a5200; }",
    "      .lab-badge.thumbnail_generated { background: #f5f5f5; color: #666; }",
    "      .lab-badge.thumbnail_approved { background: #e9f7f4; color: #166f62; }",
    "      .lab-badge.thumbnail_rejected { background: #fff3e6; color: #8a5200; }",
    "      .lab-badge.disqualified,",
    "      .lab-badge.rejected { background: #fff3e6; color: #8a5200; }",
    "      .lab-badge.generated,",
    "      .lab-badge.api_pending,",
    "      .lab-badge.draft { background: #f5f5f5; color: #666; }",
    "      .lab-badge.archived { background: #f3f3f3; color: #777; }",
    "      .lab-chip-row {",
    "        display: flex;",
    "        flex-wrap: wrap;",
    "        gap: 6px;",
    "      }",
    "      .lab-chip {",
    "        display: inline-flex;",
    "        align-items: center;",
    "        padding: 4px 9px;",
    "        border-radius: 999px;",
    "        font-size: 12px;",
    "        font-weight: 650;",
    "        line-height: 1;",
    "        white-space: nowrap;",
    "      }",
    "      .lab-chip.blue { background: #eaf1ff; color: #2e63b7; }",
    "      .lab-chip.purple { background: #f1ebff; color: #6a44b8; }",
    "      .lab-chip.orange { background: #fff0df; color: #b46406; }",
    "      .lab-chip.green { background: #eaf7ea; color: #2f7a34; }",
    "      .lab-chip.default { background: #f3f3f3; color: #555; }",
    "      .lab-status-copy {",
    "        margin-top: 12px;",
    "        color: var(--muted);",
    "        font-size: 13px;",
    "      }",
    "      .lab-alert {",
    "        margin-top: 14px;",
    "        padding: 14px 16px;",
    "        border-radius: 8px;",
    "        border: 1px solid transparent;",
    "        font-size: 14px;",
    "        line-height: 1.5;",
    "      }",
    "      .lab-alert-error {",
    "        background: #fdecea;",
    "        color: #5d1212;",
    "        border-color: #f3b8b3;",
    "        box-shadow: 0 0 0 2px rgba(243, 184, 179, 0.35);",
    "      }",
    "      .lab-alert-error .lab-alert-title {",
    "        display: flex;",
    "        align-items: center;",
    "        gap: 8px;",
    "        font-size: 15px;",
    "        font-weight: 700;",
    "        color: #7a1a1a;",
    "        margin-bottom: 6px;",
    "      }",
    "      .lab-alert-error .lab-alert-icon {",
    "        font-size: 18px;",
    "        color: #b3261e;",
    "      }",
    "      .lab-alert-error .lab-alert-time {",
    "        font-weight: 500;",
    "        color: #8a3a3a;",
    "        margin-left: 4px;",
    "      }",
    "      .lab-alert-error .lab-alert-body {",
    "        color: #4a1313;",
    "      }",
    "      .lab-alert-error .lab-alert-body p {",
    "        margin: 6px 0;",
    "      }",
    "      .lab-alert-error .lab-alert-body ul {",
    "        margin: 6px 0 6px 20px;",
    "        padding: 0;",
    "      }",
    "      .lab-alert-error .lab-alert-body li {",
    "        margin-bottom: 3px;",
    "      }",
    "      .lab-alert-error .lab-alert-body code {",
    "        background: rgba(122, 26, 26, 0.08);",
    "        padding: 1px 5px;",
    "        border-radius: 3px;",
    "        font-size: 13px;",
    "      }",
    "      .research-inline-summary {",
    "        color: var(--ink);",
    "        font-size: 15px;",
    "        line-height: 1.65;",
    "        white-space: normal;",
    "      }",
    "      .research-summary-line { margin: 0 0 9px; }",
    "      .research-summary-heading {",
    "        margin-top: 16px;",
    "        color: var(--ink);",
    "        font-weight: 760;",
    "      }",
    "      .research-summary-list-item {",
    "        display: grid;",
    "        grid-template-columns: 28px 1fr;",
    "        gap: 6px;",
    "        margin-bottom: 7px;",
    "      }",
    "      .research-summary-list-prefix { color: var(--muted); font-weight: 700; }",
    "      .research-summary-spacer { height: 8px; }",
    "      .research-citation-marker.btn {",
    "        display: inline-flex;",
    "        align-items: center;",
    "        justify-content: center;",
    "        position: relative;",
    "        min-width: 0;",
    "        width: auto;",
    "        height: 20px;",
    "        padding: 0 5px;",
    "        margin: 0 2px 0 3px;",
    "        border-radius: 999px;",
    "        font-size: 11px;",
    "        line-height: 1;",
    "        vertical-align: super;",
    "      }",
    "      .research-citation-marker.status-evidence_not_fetched { border-color: #cfd8dc; background: #f5f7f8; color: #52616a; }",
    "      .research-citation-marker.status-suggested { border-color: #a8c7fa; background: #eef4ff; color: #2757a3; }",
    "      .research-citation-marker.status-supports { border-color: #a8d5ad; background: #eaf7ea; color: #216d2a; }",
    "      .research-citation-marker.status-partially_supports { border-color: #b7c9f2; background: #eef4ff; color: #2757a3; }",
    "      .research-citation-marker.status-generally_supported_no_direct_quote { border-color: #d6c78b; background: #fff9e6; color: #735c00; }",
    "      .research-citation-marker.status-weak_support { border-color: #e0c36a; background: #fff8db; color: #806000; }",
    "      .research-citation-marker.status-contradicts { border-color: #f0a3a3; background: #fff0f0; color: #9a1b1b; }",
    "      .research-citation-marker.status-verified { border-color: #a8d5ad; background: #eaf7ea; color: #216d2a; }",
    "      .research-citation-marker.status-rejected { border-color: #f2b8a2; background: #fff3e6; color: #8a5200; }",
    "      .research-citation-marker.status-no_match { border-color: #e0c36a; background: #fff8db; color: #806000; }",
    "      .research-evidence-review-layout {",
    "        display: block;",
    "      }",
    "      .research-evidence-summary-pane {",
    "        min-width: 0;",
    "        max-width: 760px;",
    "      }",
    "      .app-shell-v2 .research-evidence-summary-pane.lab-card {",
    "        max-width: 760px;",
    "      }",
    "      body:has(.research-evidence-side-overlay:not(.hidden)) .app-shell-v2 .main {",
    "        padding-right: 470px;",
    "      }",
    "      .research-evidence-side-overlay {",
    "        position: fixed;",
    "        top: 70px;",
    "        right: 24px;",
    "        bottom: 24px;",
    "        width: 420px;",
    "        max-width: calc(100vw - 320px);",
    "        z-index: 3000;",
    "        overflow-y: auto;",
    "        border: 1px solid var(--line, #d7dee3);",
    "        border-radius: 12px;",
    "        background: #ffffff;",
    "        box-shadow: 0 18px 50px rgba(20, 31, 43, 0.18);",
    "        display: flex;",
    "        flex-direction: column;",
    "      }",
    "      .research-evidence-side-overlay.hidden { display: none; }",
    "      .research-evidence-side-overlay-empty {",
    "        border-style: dashed;",
    "        background: #fbfcfc;",
    "      }",
    "      .research-evidence-side-overlay-header {",
    "        display: flex;",
    "        align-items: center;",
    "        justify-content: space-between;",
    "        gap: 14px;",
    "        padding: 13px 16px;",
    "        border-bottom: 1px solid #edf0f2;",
    "        background: #fbfcfc;",
    "      }",
    "      .research-evidence-panel-body {",
    "        overflow-y: auto;",
    "        padding: 14px 16px 18px;",
    "      }",
    "      .research-evidence-selected-summary {",
    "        margin-bottom: 14px;",
    "        padding: 11px 12px;",
    "        border-radius: 8px;",
    "        background: #f5faf5;",
    "      }",
    "      .research-evidence-selected-summary strong {",
    "        display: block;",
    "        margin-bottom: 5px;",
    "        color: var(--muted);",
    "        font-size: 11px;",
    "        text-transform: uppercase;",
    "        letter-spacing: .04em;",
    "      }",
    "      .research-evidence-selected-summary p { margin: 0; color: var(--ink); line-height: 1.45; }",
    "      .research-evidence-claim-section {",
    "        padding: 14px 0;",
    "        border-top: 1px solid #edf0f2;",
    "      }",
    "      .research-evidence-claim-section:first-of-type { border-top: 0; padding-top: 0; }",
    "      .research-evidence-claim-header {",
    "        display: flex;",
    "        align-items: center;",
    "        justify-content: space-between;",
    "        gap: 12px;",
    "        margin-bottom: 8px;",
    "      }",
    "      .research-evidence-claim-header h5 { margin: 0; color: var(--ink); font-weight: 760; }",
    "      .research-evidence-claim-text {",
    "        margin: 0 0 9px;",
    "        color: var(--ink);",
    "        line-height: 1.45;",
    "      }",
    "      .research-evidence-status-pill {",
    "        display: inline-flex;",
    "        align-items: center;",
    "        min-height: 22px;",
    "        padding: 2px 8px;",
    "        border: 1px solid #d7dee3;",
    "        border-radius: 999px;",
    "        background: #f5f7f8;",
    "        color: #52616a;",
    "        font-size: 11px;",
    "        font-weight: 760;",
    "        white-space: nowrap;",
    "      }",
    "      .research-evidence-status-pill.status-supports,",
    "      .research-evidence-status-pill.status-verified { border-color: #a8d5ad; background: #eaf7ea; color: #216d2a; }",
    "      .research-evidence-status-pill.status-partially_supports { border-color: #b7c9f2; background: #eef4ff; color: #2757a3; }",
    "      .research-evidence-status-pill.status-generally_supported_no_direct_quote,",
    "      .research-evidence-status-pill.status-weak_support,",
    "      .research-evidence-status-pill.status-no_match { border-color: #e0c36a; background: #fff8db; color: #806000; }",
    "      .research-evidence-status-pill.status-contradicts,",
    "      .research-evidence-status-pill.status-rejected { border-color: #f0a3a3; background: #fff0f0; color: #9a1b1b; }",
    "      .research-citation-tooltip {",
    "        display: none;",
    "        position: absolute;",
    "        left: 50%;",
    "        bottom: calc(100% + 9px);",
    "        transform: translateX(-50%);",
    "        z-index: 2500;",
    "        width: 260px;",
    "        max-width: 32vw;",
    "        max-height: 140px;",
    "        overflow: hidden;",
    "        padding: 10px 12px;",
    "        border: 1px solid #ccd4da;",
    "        border-radius: 8px;",
    "        background: #ffffff;",
    "        box-shadow: 0 10px 28px rgba(20, 31, 43, .18);",
    "        color: var(--ink);",
    "        font-size: 12px;",
    "        font-weight: 500;",
    "        line-height: 1.35;",
    "        text-align: left;",
    "        white-space: normal;",
    "        pointer-events: none;",
    "      }",
    "      .research-citation-marker:hover .research-citation-tooltip,",
    "      .research-citation-marker:focus .research-citation-tooltip { display: block; }",
    "      .research-citation-tooltip-label,",
    "      .research-pdf-quote-label {",
    "        display: block;",
    "        color: #52616a;",
    "        font-size: 11px;",
    "        font-weight: 760;",
    "        text-transform: uppercase;",
    "        letter-spacing: .04em;",
    "      }",
    "      .research-citation-tooltip-quote,",
    "      .research-pdf-quote {",
    "        display: block;",
    "        margin-top: 6px;",
    "        padding: 9px 11px;",
    "        border-left: 3px solid #1a8917;",
    "        border-radius: 6px;",
    "        background: #f7fbf7;",
    "        color: var(--ink);",
    "        font-style: italic;",
    "        line-height: 1.4;",
    "      }",
    "      .research-citation-tooltip-quote::before,",
    "      .research-pdf-quote::before { content: '\"'; }",
    "      .research-citation-tooltip-quote::after,",
    "      .research-pdf-quote::after { content: '\"'; }",
    "      .research-citation-tooltip-quote {",
    "        max-height: 104px;",
    "        overflow: hidden;",
    "      }",
    "      .research-citation-tooltip-quote-preview {",
    "        display: block;",
    "        margin-top: 6px;",
    "        color: var(--ink);",
    "        font-size: 11px;",
    "        font-style: italic;",
    "        line-height: 1.35;",
    "      }",
    "      .research-citation-tooltip-quote-preview::before { content: '\"'; }",
    "      .research-citation-tooltip-quote-preview::after { content: '\"'; }",
    "      .research-citation-tooltip-claim {",
    "        display: block;",
    "        margin-top: 5px;",
    "        color: var(--ink);",
    "        font-weight: 600;",
    "      }",
    "      .research-citation-tooltip-meta,",
    "      .research-citation-tooltip-reason {",
    "        display: block;",
    "        margin-top: 6px;",
    "        color: #52616a;",
    "        font-size: 11px;",
    "        line-height: 1.35;",
    "      }",
    "      .research-pdf-quote-label { margin-top: 14px; }",
    "      .research-pdf-quote {",
    "        margin-top: 7px;",
    "        font-size: 14px;",
    "        font-style: normal;",
    "      }",
    "      .research-citation-marker.active,",
    "      .research-citation-marker:focus {",
    "        border-color: #1a8917;",
    "        background: #e8f4ea;",
    "        color: #176d14;",
    "      }",
    "      .research-evidence-drawer { display: none; }",
    "      .research-evidence-drawer-header {",
    "        display: flex;",
    "        align-items: center;",
    "        justify-content: space-between;",
    "        gap: 18px;",
    "        padding: 12px 18px;",
    "        border-bottom: 1px solid #edf0f2;",
    "        background: #fbfcfc;",
    "      }",
    "      .research-evidence-drawer-title { color: var(--ink); font-weight: 760; }",
    "      .research-evidence-drawer-subtitle { margin-top: 3px; color: var(--muted); font-size: 12px; }",
    "      .research-evidence-drawer-close.btn { min-width: 76px; height: 34px; padding: 0 12px; }",
    "      .research-evidence-drawer-body {",
    "        overflow-y: auto;",
    "        padding: 4px 20px 22px;",
    "      }",
    "      @media (max-width: 1180px) {",
    "        .research-evidence-side-overlay {",
    "          left: 24px;",
    "          right: 24px;",
    "          width: auto;",
    "          max-width: none;",
    "        }",
    "        body:has(.research-evidence-side-overlay:not(.hidden)) .app-shell-v2 .main {",
    "          padding-right: 28px;",
    "        }",
    "      }",
    "      .lab-inline-notice {",
    "        margin-top: 12px;",
    "        padding: 10px 12px;",
    "        border: 1px solid #dceedd;",
    "        border-radius: 8px;",
    "        background: #fbfefb;",
    "        color: #2b642e;",
    "        font-size: 13px;",
    "        line-height: 1.35;",
    "      }",
    "      .lab-empty-state {",
    "        display: grid;",
    "        gap: 6px;",
    "      }",
    "      .lab-empty-state strong {",
    "        color: var(--ink);",
    "        font-size: 14px;",
    "      }",
    "      .lab-empty-state p {",
    "        margin: 0;",
    "        line-height: 1.4;",
    "      }",
    "      .lab-empty-next {",
    "        color: #4c6c51;",
    "      }",
    "      .lab-secondary-details {",
    "        margin-top: 14px;",
    "        border: 1px solid #ededed;",
    "        border-radius: 8px;",
    "        padding: 10px 12px;",
    "        background: #fbfbfb;",
    "      }",
    "      .lab-secondary-details > summary,",
    "      .lab-card details > summary {",
    "        cursor: pointer;",
    "        font-weight: 700;",
    "        color: var(--ink);",
    "      }",
    "      .lab-secondary-details .lab-card,",
    "      .lab-card .lab-secondary-details .lab-card {",
    "        border: 0;",
    "        padding: 0;",
    "        margin-top: 12px;",
    "        background: transparent;",
    "      }",
    "      .approved-subtitle-list {",
    "        display: grid;",
    "        gap: 8px;",
    "      }",
    "      .approved-subtitle-item {",
    "        padding: 7px 10px;",
    "        border-radius: 8px;",
    "        background: #f7f7f7;",
    "        line-height: 1.35;",
    "      }",
    "      .thumbnail-preview-grid {",
    "        display: grid;",
    "        gap: 18px;",
    "        margin-top: 8px;",
    "        max-width: 760px;",
    "      }",
    "      .thumbnail-preview-card {",
    "        border: 1px solid var(--line);",
    "        border-radius: 8px;",
    "        background: #fff;",
    "        padding: 14px 18px 18px;",
    "        box-shadow: none;",
    "        max-width: 760px;",
    "      }",
    "      .thumbnail-preview-card.lab-selected-card,",
    "      .thumbnail-preview-card:has(input[type='checkbox']:checked) {",
    "        border-color: #9bc99e;",
    "        background: #f4fbf5;",
    "        box-shadow: inset 3px 0 0 var(--green);",
    "      }",
    "      .thumbnail-preview-card.approved {",
    "        border-color: #dceedd;",
    "        background: #fbfefb;",
    "      }",
    "      .thumbnail-preview-card.approved.lab-selected-card,",
    "      .thumbnail-preview-card.approved:has(input[type='checkbox']:checked) {",
    "        border-color: #9bc99e;",
    "        background: #f1faf2;",
    "      }",
    "      .thumbnail-preview-topbar {",
    "        display: flex;",
    "        align-items: center;",
    "        justify-content: space-between;",
    "        gap: 10px;",
    "        margin-bottom: 12px;",
    "      }",
    "      .thumbnail-preview-topbar .checkbox {",
    "        margin: 0;",
    "      }",
    "      .thumbnail-preview-shell {",
    "        display: grid;",
    "        grid-template-columns: minmax(0, 1fr) 170px;",
    "        gap: 32px;",
    "        align-items: center;",
    "      }",
    "      .thumbnail-preview-image-wrap {",
    "        border-radius: 1px;",
    "        overflow: hidden;",
    "        background: #fff;",
    "        display: flex;",
    "        justify-content: flex-end;",
    "        align-items: center;",
    "      }",
    "      .thumbnail-preview-image {",
    "        width: 170px;",
    "        height: 113px;",
    "        object-fit: cover;",
    "        display: block;",
    "        border: 0;",
    "      }",
    "      .medium-preview-card {",
    "        border: 0;",
    "        border-radius: 0;",
    "        padding: 0;",
    "        background: transparent;",
    "        min-width: 0;",
    "      }",
    "      .preview-kicker {",
    "        font-size: 11px;",
    "        font-weight: 700;",
    "        letter-spacing: .02em;",
    "        text-transform: uppercase;",
    "        color: var(--green);",
    "        margin-bottom: 8px;",
    "      }",
    "      .preview-title {",
    "        font-size: 26px;",
    "        line-height: 1.15;",
    "        font-weight: 760;",
    "        color: var(--ink);",
    "        margin-bottom: 8px;",
    "      }",
    "      .preview-subtitle {",
    "        color: var(--muted);",
    "        font-size: 18px;",
    "        line-height: 1.35;",
    "      }",
    "      .thumbnail-preview-card .shiny-input-container {",
    "        width: 100%;",
    "        margin-top: 12px;",
    "        margin-bottom: 0;",
    "      }",
    "      .status-card {",
    "        padding: 14px 16px;",
    "        margin-bottom: 12px;",
    "      }",
    "      .status-card h3 {",
    "        margin: 0 0 8px;",
    "        font-size: 16px;",
    "        font-weight: 760;",
    "      }",
    "      .status-card p,",
    "      .status-card li {",
    "        margin: 0;",
    "        color: #333;",
    "        line-height: 1.4;",
    "        font-size: 13px;",
    "      }",
    "      .status-card .status-metric {",
    "        color: var(--green);",
    "        font-size: 24px;",
    "        font-weight: 760;",
    "        line-height: 1;",
    "        margin-bottom: 8px;",
    "      }",
    "      .overview-metric-list {",
    "        display: grid;",
    "        gap: 14px;",
    "      }",
    "      .overview-metric {",
    "        display: grid;",
    "        grid-template-columns: 34px minmax(0, 1fr);",
    "        gap: 10px;",
    "        align-items: center;",
    "      }",
    "      .overview-metric-value {",
    "        color: #2e63b7;",
    "        font-size: 24px;",
    "        font-weight: 760;",
    "        line-height: 1;",
    "      }",
    "      .overview-metric-value.green { color: var(--green); }",
    "      .empty-state {",
    "        max-width: 760px;",
    "        margin-top: 12px;",
    "        padding: 18px 20px;",
    "        color: var(--muted);",
    "        font-size: 14px;",
    "      }",
    "      .lab-publish-status-row {",
    "        margin-top: 16px;",
    "        display: flex;",
    "        gap: 8px;",
    "        flex-wrap: wrap;",
    "      }",
    "      .lab-publish-workspace {",
    "        display: grid;",
    "        grid-template-columns: minmax(0, 1fr);",
    "        gap: 18px;",
    "        align-items: start;",
    "      }",
    "      .lab-publish-workspace .lab-card {",
    "        max-width: none;",
    "      }",
    "      .lab-publish-preview .thumbnail-preview-image-wrap {",
    "        justify-content: flex-start;",
    "        margin: 14px 0;",
    "      }",
    "      .lab-readonly-preview {",
    "        max-height: 520px;",
    "        overflow: auto;",
    "        white-space: pre-wrap;",
    "        overflow-wrap: anywhere;",
    "        padding: 12px;",
    "        border: 1px solid #ececec;",
    "        border-radius: 8px;",
    "        background: #f9f9f9;",
    "      }",
    "      .step-placeholder {",
    "        display: grid;",
    "        gap: 12px;",
    "      }",
    "      .guide-section { border-bottom: 1px solid var(--line); padding: 10px 0 16px; }",
    "      .guide-section:first-child { padding-top: 0; }",
    "      .guide-section:last-child { border-bottom: 0; }",
    "      .guide h3 { font-size: 16px; margin: 0 0 10px; font-weight: 750; }",
    "      .guide p, .guide li { color: #333; line-height: 1.34; font-size: 13px; }",
    "      .guide ul { padding-left: 18px; margin: 0; }",
    "      .guide li { margin-bottom: 5px; }",
    "      .guide .tip {",
    "        background: var(--green-soft); border-radius: 8px; padding: 14px;",
    "        position: absolute;",
    "        left: 20px;",
    "        right: 20px;",
    "      }",
    "      .done-state {",
    "        border: 1px solid var(--line); border-radius: 8px; padding: 42px; margin-top: 28px; text-align: center;",
    "      }",
    v2_css,
    "      @media (max-width: 1180px) {",
    "        .app-shell { grid-template-columns: 86px minmax(520px, 1fr); }",
    "        .guide { display: none; }",
    "        .sidebar { padding: 24px 14px; }",
    "        .nav-copy, .daily-goal { display: none; }",
    "        .nav-item { grid-template-columns: 1fr; justify-items: center; padding: 12px 10px; }",
    "      }",
    "      @media (max-width: 820px) {",
    "        .stage-one-hero, .evidence-idea-header { align-items: flex-start; flex-direction: column; }",
    "        .placeholder-meta-grid, .evidence-grid { grid-template-columns: 1fr; }",
    "        .title-lab-flow { overflow-x: auto; white-space: nowrap; }",
    "        .app-shell { display: block; }",
    "        .sidebar { display: none; }",
    "        .main { padding: 28px 18px; }",
    "        .lab-grid { grid-template-columns: 1fr; }",
    "        .dataTables_wrapper { max-width: 100%; overflow-x: auto; }",
    "        .dataTables_wrapper table.dataTable { min-width: 700px !important; }",
    "        .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_length { float: none; text-align: left; }",
    "        .lab-publish-workspace { grid-template-columns: 1fr; }",
    "        .article-card { grid-template-columns: 1fr; gap: 18px; padding: 24px 0 26px; }",
    "        .article-card.thumbnail-only { grid-template-columns: 170px; }",
    "        .article-card.text-only { grid-template-columns: 1fr; }",
    "        .thumbnail-preview-shell { grid-template-columns: 1fr; gap: 18px; }",
    "        .thumbnail-preview-grid { max-width: none; }",
    "        .thumbnail-preview-card { padding: 14px 14px 16px; }",
    "        .thumbnail-wrap { justify-content: flex-start; }",
    "        .thumbnail-wrap .shiny-image-output,",
    "        .thumbnail-wrap img,",
    "        .thumbnail-placeholder,",
    "        .thumbnail-preview-image { width: 100% !important; height: auto !important; aspect-ratio: 1.5; }",
    "        .rating-buttons { gap: 8px; }",
    "        .rating-buttons .btn { height: 52px; font-size: 21px; }",
    "        .dimension-row { grid-template-columns: 1fr; }",
    "        .dimension-buttons { justify-content: stretch; }",
    "        .dimension-choice.btn { flex: 1; }",
    "      }"
  ), collapse = "\n"))
}

article_lab_js <- function(is_dimension_mode_value = get0("is_dimension_mode", inherits = TRUE, ifnotfound = FALSE)) {
  HTML(paste0(
      "window.__dimensionMode = ", if (isTRUE(is_dimension_mode_value)) "true" else "false", ";\n",

      paste(c(
        "",
        "      function flashAndSubmitRating(score) {",
        "        const button = document.getElementById('score_' + score);",
        "        if (button) {",
        "          document.querySelectorAll('.rating-buttons .btn').forEach(function(oneButton) {",
        "            oneButton.classList.remove('rating-confirm');",
        "          });",
        "          button.classList.add('rating-confirm');",
        "        }",
        "        window.setTimeout(function() {",
        "          Shiny.setInputValue('score_key', {score: Number(score), nonce: Date.now()}, {priority: 'event'});",
        "        }, 70);",
        "      }",
        "",
        "      function flashAndSubmitDimension(field, value) {",
        "        const selector = '.dimension-choice[data-field=\"' + field + '\"][data-value=\"' + value + '\"]';",
        "        const button = document.querySelector(selector);",
        "        if (button) {",
        "          document.querySelectorAll('.dimension-choice').forEach(function(oneButton) {",
        "            oneButton.classList.remove('dimension-confirm');",
        "          });",
        "          button.classList.add('dimension-confirm');",
        "        }",
        "        window.setTimeout(function() {",
        "          Shiny.setInputValue('dimension_select', {",
        "            field: field,",
        "            value: value,",
        "            nonce: Date.now()",
        "          }, {priority: 'event'});",
        "        }, 23);",
        "      }",
        "",
        "      function copyVerificationTitle(element) {",
        "        if (!element) return;",
        "        const title = element.getAttribute('data-copy-title') || element.textContent || '';",
        "        const done = function() {",
        "          element.classList.add('copied');",
        "          const original = element.getAttribute('data-original-title') || title;",
        "          element.setAttribute('data-original-title', original);",
        "          element.textContent = 'Copied title';",
        "          window.setTimeout(function() {",
        "            element.classList.remove('copied');",
        "            element.textContent = original;",
        "          }, 850);",
        "        };",
        "        if (navigator.clipboard && navigator.clipboard.writeText) {",
        "          navigator.clipboard.writeText(title).then(done).catch(function() {",
        "            window.prompt('Copy title', title);",
        "          });",
        "        } else {",
        "          window.prompt('Copy title', title);",
        "        }",
        "      }",
        "",
        "      function articleLabCopyTextFromElement(elementId, button, label) {",
        "        const element = document.getElementById(elementId);",
        "        if (!element) return;",
        "        const text = element.textContent || '';",
        "        const originalLabel = button ? button.textContent : '';",
        "        const done = function() {",
        "          if (!button) return;",
        "            button.textContent = label || 'Copied prompt';",
        "          window.setTimeout(function() {",
        "            button.textContent = originalLabel || 'Copy prompt';",
        "          }, 1100);",
        "        };",
        "        if (navigator.clipboard && navigator.clipboard.writeText) {",
        "          navigator.clipboard.writeText(text).then(done).catch(function() {",
        "            window.prompt('Copy prompt', text);",
        "          });",
        "        } else {",
        "          window.prompt('Copy prompt', text);",
        "        }",
        "      }",
        "",
        "      function articleLabCopyValueFromElement(elementId, button, label) {",
        "        const element = document.getElementById(elementId);",
        "        if (!element) return;",
        "        const text = typeof element.value === 'string' ? element.value : (element.textContent || '');",
        "        const originalLabel = button ? button.textContent : '';",
        "        const copiedLabel = label || 'Copied';",
        "        const done = function() {",
        "          if (!button) return;",
        "          button.textContent = copiedLabel;",
        "          window.setTimeout(function() {",
        "            button.textContent = originalLabel || 'Copy';",
        "          }, 1100);",
        "        };",
        "        if (navigator.clipboard && navigator.clipboard.writeText) {",
        "          navigator.clipboard.writeText(text).then(done).catch(function() {",
        "            window.prompt('Copy text', text);",
        "          });",
        "        } else {",
        "          window.prompt('Copy text', text);",
        "        }",
        "      }",
        "",
        "      function alignSideCardsToRatingPanel() {",
        "        const ratingPanel = document.querySelector('.rating-panel');",
        "        const sidebar = document.querySelector('.sidebar');",
        "        const guide = document.querySelector('.guide');",
        "        const dailyGoal = document.querySelector('.daily-goal');",
        "        const tip = document.querySelector('.guide .tip');",
        "        if (!ratingPanel || !sidebar || !guide || !dailyGoal || !tip) return;",
        "",
        "        const ratingBottom = ratingPanel.getBoundingClientRect().bottom;",
        "        const sidebarTop = sidebar.getBoundingClientRect().top;",
        "        const guideTop = guide.getBoundingClientRect().top;",
        "        const tipTop = Math.max(22, ratingBottom - guideTop - tip.offsetHeight);",
        "        if (window.getComputedStyle(dailyGoal).position === 'absolute') {",
        "          const dailyTop = Math.max(22, ratingBottom - sidebarTop - dailyGoal.offsetHeight);",
        "          dailyGoal.style.top = dailyTop + 'px';",
        "        }",
        "        tip.style.top = tipTop + 'px';",
        "      }",
        "",
        "      function articleLabSyncSelections(groupName) {",
        "        if (!groupName || typeof Shiny === 'undefined' || typeof Shiny.setInputValue !== 'function') return;",
        "        const selectedIds = [];",
        "        const rows = Array.from(document.querySelectorAll('[data-selection-group=\"' + groupName + '\"]'));",
        "        if (rows.length > 0) {",
        "          rows",
        "            .filter(function(row) {",
        "              const checkbox = row.querySelector('input[type=\"checkbox\"]');",
        "              return !!(checkbox && checkbox.checked);",
        "            })",
        "            .map(function(row) {",
        "              return row.getAttribute('data-candidate-id');",
        "            })",
        "            .filter(function(value) {",
        "              return !!value;",
        "            })",
        "            .forEach(function(id) {",
        "              if (selectedIds.indexOf(id) < 0) selectedIds.push(id);",
        "            });",
        "        }",
        "        const inputPrefix = groupName + '_';",
        "        const directInputs = Array.from(document.querySelectorAll('input[type=\"checkbox\"][id^=\"' + inputPrefix + '\"]'));",
        "        if (directInputs.length > 0) {",
        "          directInputs",
        "            .filter(function(checkbox) { return checkbox.checked; })",
        "            .map(function(checkbox) { return checkbox.id.slice(inputPrefix.length); })",
        "            .filter(function(value) { return !!value; })",
        "            .forEach(function(id) {",
        "              if (selectedIds.indexOf(id) < 0) selectedIds.push(id);",
        "            });",
        "        }",
        "        Shiny.setInputValue(groupName + '_selected_snapshot', selectedIds, { priority: 'event' });",
        "      }",
        "",
      "      function articleLabRefreshSelectionState(root) {",
      "        const scope = root || document;",
      "        scope.querySelectorAll('[data-selection-group]').forEach(function(item) {",
        "          const checkbox = item.querySelector('input[type=\"checkbox\"]');",
        "          const selected = !!(checkbox && checkbox.checked);",
        "          item.classList.toggle('lab-selected-row', selected && item.tagName === 'TR');",
        "          item.classList.toggle('lab-selected-card', selected && item.tagName !== 'TR');",
      "        });",
      "      }",
      "",
      "      function articleLabApplyFullTextSingleSelection(changedCheckbox) {",
      "        if (!changedCheckbox || !changedCheckbox.checked) return;",
      "        const item = changedCheckbox.closest('[data-selection-group]');",
      "        if (!item) return;",
      "        const groupName = item.getAttribute('data-selection-group');",
      "        const fullTextGroups = ['article_lab_full_text_packages', 'article_lab_full_text_drafts'];",
      "        if (fullTextGroups.indexOf(groupName) < 0) return;",
      "        fullTextGroups.forEach(function(currentGroup) {",
      "          document.querySelectorAll('[data-selection-group=\"' + currentGroup + '\"] input[type=\"checkbox\"]').forEach(function(checkbox) {",
      "            if (checkbox !== changedCheckbox) checkbox.checked = false;",
      "          });",
      "        });",
      "      }",
      "",
      "      document.addEventListener('change', function(event) {",
      "        if (!event.target || !event.target.matches('input[type=\"checkbox\"]')) return;",
      "        articleLabApplyFullTextSingleSelection(event.target);",
      "        articleLabRefreshSelectionState(document);",
      "      });",
        "",
        "      window.articleLabSyncSelections = articleLabSyncSelections;",
        "      window.articleLabRefreshSelectionState = articleLabRefreshSelectionState;",
        "      window.articleLabCopyTextFromElement = articleLabCopyTextFromElement;",
        "      window.articleLabCopyValueFromElement = articleLabCopyValueFromElement;",
        "",
        "      let articleLabThumbnailTimer = null;",
        "",
        "      function articleLabFormatDuration(totalSeconds) {",
        "        totalSeconds = Math.max(0, Math.round(Number(totalSeconds) || 0));",
        "        const minutes = Math.floor(totalSeconds / 60);",
        "        const seconds = totalSeconds % 60;",
        "        if (minutes <= 0) return seconds + ' sec';",
        "        if (seconds === 0) return minutes + ' min';",
        "        return minutes + ' min ' + seconds + ' sec';",
        "      }",
        "",
        "      function articleLabFormatClock(timestamp) {",
        "        const date = new Date(timestamp);",
        "        if (Number.isNaN(date.getTime())) return '';",
        "        return date.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });",
        "      }",
        "",
        "      function articleLabSetThumbnailStatus(copy) {",
        "        const target = document.getElementById('article_lab_thumbnail_timer');",
        "        if (target) target.textContent = copy || '';",
        "      }",
        "",
        "      function articleLabStartThumbnailTimer(payload) {",
        "        if (articleLabThumbnailTimer) window.clearInterval(articleLabThumbnailTimer);",
        "        const startedAt = payload && payload.started_at ? new Date(payload.started_at) : new Date();",
        "        const totalExpected = Math.max(1, Number(payload && payload.total_expected) || 1);",
        "        const estimateLabel = payload && payload.estimate_label ? payload.estimate_label : '';",
        "        const upperSeconds = Math.max(1, Number(payload && payload.upper_seconds) || 1);",
        "        const startedLabel = articleLabFormatClock(startedAt);",
        "        const render = function() {",
        "          const elapsedSeconds = Math.max(0, (Date.now() - startedAt.getTime()) / 1000);",
        "          let copy = 'Generating thumbnails: requested ' + totalExpected + ' thumbnail' + (totalExpected === 1 ? '' : 's') + '.';",
        "          if (startedLabel) copy += ' Started ' + startedLabel + '.';",
        "          if (estimateLabel) copy += ' Initial estimate: ' + estimateLabel + '.';",
        "          copy += ' Elapsed: ' + articleLabFormatDuration(elapsedSeconds) + '.';",
        "          if (elapsedSeconds > upperSeconds) {",
        "            copy += ' Still running, slower than the initial estimate. True completed/remaining progress is not available until this blocking OpenAI call finishes.';",
        "          } else {",
        "            copy += ' Waiting for OpenAI; true completed/remaining progress is not available during this blocking call.';",
        "          }",
        "          articleLabSetThumbnailStatus(copy);",
        "        };",
        "        render();",
        "        articleLabThumbnailTimer = window.setInterval(render, 1000);",
        "      }",
        "",
        "      function articleLabStopThumbnailTimer(payload) {",
        "        if (articleLabThumbnailTimer) {",
        "          window.clearInterval(articleLabThumbnailTimer);",
        "          articleLabThumbnailTimer = null;",
        "        }",
        "        articleLabSetThumbnailStatus(payload && payload.message ? payload.message : '');",
        "      }",
        "",
        "      function setWorkflowLayout(layoutName) {",
        "        const appShell = document.querySelector('.app-shell');",
        "        const main = document.querySelector('.main');",
        "        const guide = document.querySelector('.guide');",
        "        const wideSections = ['research_inbox', 'summary', 'article_evidence', 'title_lab', 'generate', 'api_scoring', 'subtitle_generation', 'thumbnails', 'outline', 'full_text', 'review_publish', 'settings'];",
        "        const useWideLayout = wideSections.indexOf(layoutName) >= 0;",
        "        if (appShell) appShell.classList.toggle('workflow-wide-layout', useWideLayout);",
        "        if (main) main.classList.toggle('workflow-wide-main', useWideLayout);",
        "        if (guide) guide.classList.toggle('guide-hidden', useWideLayout);",
        "      }",
        "",
        "      window.addEventListener('resize', function() {",
        "        window.requestAnimationFrame(alignSideCardsToRatingPanel);",
        "      });",
        "      document.addEventListener('DOMContentLoaded', function() {",
        "        window.setTimeout(alignSideCardsToRatingPanel, 250);",
        "      });",
        "      window.setInterval(alignSideCardsToRatingPanel, 300);",
        "",
      "      document.addEventListener('click', function(event) {",
      "        const evidenceOverlay = document.querySelector('.research-evidence-side-overlay');",
      "        const evidenceMarker = event.target && event.target.closest ? event.target.closest('.research-citation-marker') : null;",
      "        const insideEvidenceOverlay = event.target && event.target.closest ? event.target.closest('.research-evidence-side-overlay') : null;",
      "        if (evidenceOverlay && !evidenceOverlay.classList.contains('hidden') && !evidenceMarker && !insideEvidenceOverlay && window.Shiny && Shiny.setInputValue) {",
      "          Shiny.setInputValue('research_close_evidence_drawer', Date.now(), {priority: 'event'});",
      "        }",
      "        const verificationTitle = event.target && event.target.closest ? event.target.closest('.dimension-verification-title') : null;",
        "        if (verificationTitle) {",
        "          event.preventDefault();",
        "          event.stopPropagation();",
        "          event.stopImmediatePropagation();",
        "          copyVerificationTitle(verificationTitle);",
        "          return;",
        "        }",
        "        const dimensionButton = event.target && event.target.closest ? event.target.closest('.dimension-choice') : null;",
        "        if (dimensionButton) {",
        "          event.preventDefault();",
        "          event.stopPropagation();",
        "          event.stopImmediatePropagation();",
        "          flashAndSubmitDimension(",
        "            dimensionButton.getAttribute('data-field'),",
        "            dimensionButton.getAttribute('data-value')",
        "          );",
        "          return;",
        "        }",
        "        const button = event.target && event.target.closest ? event.target.closest('.rating-buttons .btn') : null;",
        "        if (!button || !button.id || !button.id.match(/^score_[1-5]$/)) return;",
        "        event.preventDefault();",
        "        event.stopPropagation();",
        "        event.stopImmediatePropagation();",
        "        flashAndSubmitRating(button.id.replace('score_', ''));",
        "      }, true);",
        "",
        "      function isTextEntryTarget(target) {",
        "        if (!target) return false;",
        "        const tag = (target.tagName || '').toLowerCase();",
        "        return tag === 'textarea' ||",
        "          tag === 'input' ||",
        "          tag === 'select' ||",
        "          target.isContentEditable === true;",
        "      }",
        "",
        "      document.addEventListener('keydown', function(event) {",
        "        if (event.metaKey || event.ctrlKey || event.altKey) return;",
        "        const inText = isTextEntryTarget(event.target);",
        "        const rawKey = event.key || '';",
        "        const rawCode = event.code || '';",
        "        const digitMatch = rawKey.match(/^[1-5]$/) || rawCode.match(/^(Digit|Numpad)([1-5])$/);",
        "        const digit = digitMatch ? Number(digitMatch[2] || digitMatch[0]) : null;",
        "        const letter = rawKey.length === 1 ? rawKey.toLowerCase() : rawCode.replace(/^Key/, '').toLowerCase();",
        "        const homeRowRatings = {a: 1, s: 2, d: 3, f: 4, j: 5};",
        "",
        "        if (inText) {",
        "          const note = document.getElementById('note');",
        "          const noteFocused = note && document.activeElement === note;",
        "          if (noteFocused && (rawKey === 'Enter' || rawCode === 'Enter' || rawKey === 'Escape' || rawCode === 'Escape')) {",
        "            event.preventDefault();",
        "            note.dispatchEvent(new Event('change', { bubbles: true }));",
        "            note.blur();",
        "          }",
        "          return;",
        "        }",
        "",
        "        if (window.__dimensionMode) {",
        "          if (digit !== null) {",
        "            event.preventDefault();",
        "            const keyField = document.querySelector('.dimension-choice')?.getAttribute('data-field');",
        "            const flagValueMap = {'1': 'yes', '2': 'unsure', '3': 'no'};",
        "            const numericButton = document.querySelector('.dimension-choice[data-value=\"' + digit + '\"]');",
        "            const flagButton = document.querySelector('.dimension-choice[data-value=\"' + flagValueMap[String(digit)] + '\"]');",
        "            const targetButton = numericButton || flagButton;",
        "            if (keyField && targetButton) targetButton.classList.add('dimension-confirm');",
        "            window.setTimeout(function() {",
        "              Shiny.setInputValue('dimension_key', {key: String(digit), nonce: Date.now()}, {priority: 'event'});",
        "            }, 23);",
        "          } else if (['a', 's', 'd', 'f', 'j'].indexOf(letter) >= 0) {",
        "            event.preventDefault();",
        "            const keyField = document.querySelector('.dimension-choice')?.getAttribute('data-field');",
        "            const numericValueMap = {a: '1', s: '2', d: '3', f: '4', j: '5'};",
        "            const flagValueMap = {s: 'yes', d: 'unsure', j: 'no'};",
        "            const numericButton = document.querySelector('.dimension-choice[data-value=\"' + numericValueMap[letter] + '\"]');",
        "            const flagButton = document.querySelector('.dimension-choice[data-value=\"' + flagValueMap[letter] + '\"]');",
        "            const targetButton = numericButton || flagButton;",
        "            if (keyField && targetButton) targetButton.classList.add('dimension-confirm');",
        "            window.setTimeout(function() {",
        "              Shiny.setInputValue('dimension_key', {key: letter, nonce: Date.now()}, {priority: 'event'});",
        "            }, 23);",
        "          } else if (rawKey === ' ' || rawCode === 'Space') {",
        "            event.preventDefault();",
        "            Shiny.setInputValue('skip_key', Date.now(), {priority: 'event'});",
        "          } else if (letter === 'u') {",
        "            event.preventDefault();",
        "            Shiny.setInputValue('undo_key', Date.now(), {priority: 'event'});",
        "          } else if (letter === 'n') {",
        "            event.preventDefault();",
        "            const note = document.getElementById('note');",
        "            if (note) note.focus();",
        "          } else if (letter === 'r') {",
        "            event.preventDefault();",
        "            Shiny.setInputValue('dimension_reset_key', Date.now(), {priority: 'event'});",
        "          } else if (letter === 'b' || rawKey === 'Backspace' || rawCode === 'Backspace') {",
        "            event.preventDefault();",
        "            Shiny.setInputValue('dimension_back_key', Date.now(), {priority: 'event'});",
        "          }",
        "          return;",
        "        }",
        "",
        "        if (digit !== null) {",
        "          event.preventDefault();",
        "          flashAndSubmitRating(digit);",
        "        } else if (Object.prototype.hasOwnProperty.call(homeRowRatings, letter)) {",
        "          event.preventDefault();",
        "          flashAndSubmitRating(homeRowRatings[letter]);",
        "        } else if (rawKey === ' ' || rawCode === 'Space') {",
        "          event.preventDefault();",
        "          Shiny.setInputValue('skip_key', Date.now(), {priority: 'event'});",
        "        } else if (letter === 'u') {",
        "          event.preventDefault();",
        "          Shiny.setInputValue('undo_key', Date.now(), {priority: 'event'});",
        "        } else if (letter === 'n') {",
        "          event.preventDefault();",
        "          const note = document.getElementById('note');",
        "          if (note) note.focus();",
        "        }",
        "      });",
        "      function handleClearRatingFocus(_) {",
        "        document.querySelectorAll('.rating-buttons .btn').forEach(function(oneButton) {",
        "          oneButton.classList.remove('rating-confirm');",
        "        });",
        "        if (document.activeElement && document.activeElement.blur) {",
        "          document.activeElement.blur();",
        "        }",
        "        window.setTimeout(alignSideCardsToRatingPanel, 80);",
        "        window.setTimeout(alignSideCardsToRatingPanel, 260);",
        "      }",
        "      if (window.Shiny && Shiny.addCustomMessageHandler) {",
        "        Shiny.addCustomMessageHandler('clearRatingFocus', handleClearRatingFocus);",
        "        Shiny.addCustomMessageHandler('setWorkflowLayout', setWorkflowLayout);",
        "        Shiny.addCustomMessageHandler('articleLabStartThumbnailTimer', articleLabStartThumbnailTimer);",
        "        Shiny.addCustomMessageHandler('articleLabStopThumbnailTimer', articleLabStopThumbnailTimer);",
        "      } else {",
        "        document.addEventListener('shiny:connected', function() {",
        "          Shiny.addCustomMessageHandler('clearRatingFocus', handleClearRatingFocus);",
        "          Shiny.addCustomMessageHandler('setWorkflowLayout', setWorkflowLayout);",
        "          Shiny.addCustomMessageHandler('articleLabStartThumbnailTimer', articleLabStartThumbnailTimer);",
        "          Shiny.addCustomMessageHandler('articleLabStopThumbnailTimer', articleLabStopThumbnailTimer);",
        "        }, { once: true });",
        "      }"
      ), collapse = "\n"),
      "\n    "
  ))
}
